### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)

### ISSUE THREAD

**Issue by mogadanez** [orliesaurus/nodemailer-mailgun-transport#106]
after upgrade to the latest version start getting error:
```

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
at write_ (_http_outgoing.js:696:11)
at ClientRequest.write (_http_outgoing.js:661:15)
at FormData.ondata (internal/streams/legacy.js:19:31)
at FormData.emit (events.js:315:20)
at FormData.EventEmitter.emit (domain.js:467:12)
at FormData.CombinedStream.write (/api/node_modules/combined-stream/lib/combined_stream.js:138:8)
at FormData.CombinedStream._pipeNext (/api/node_modules/combined-stream/lib/combined_stream.js:126:8)
at FormData.CombinedStream._realGetNext (/api/node_modules/combined-stream/lib/combined_stream.js:99:10)
at FormData.CombinedStream._getNext (/api/node_modules/combined-stream/lib/combined_stream.js:82:12)
at FormData.CombinedStream.resume (/api/node_modules/combined-stream/lib/combined_stream.js:154:10)
at FormData.CombinedStream.pipe (/api/node_modules/combined-stream/lib/combined_stream.js:66:8)
at /api/node_modules/mailgun.js/dist/mailgun.js:2:49246
at /api/node_modules/mailgun.js/dist/mailgun.js:2:49255
at new Promise (<anonymous>)
at I (/api/node_modules/mailgun.js/dist/mailgun.js:2:45005)
at global.fetch.global.fetch (/api/node_modules/mailgun.js/dist/mailgun.js:2:27367)

```

**Comment by orliesaurus** [comment]
@mogadanez - can you share the code you're using please to send emails?

**Comment by idandagan1** [comment]
Any progress on that?
I'm getting the same issue after upgrading to 2.1.3

**Comment by orliesaurus** [comment]
> Any progress on that?
> I'm getting the same issue after upgrading to 2.1.3

Can you share the code that you re using to get this error?
