### ISSUE TITLE
Suppress Fetch API Experimental warning

### ISSUE THREAD

**Issue by epaminond** [orliesaurus/nodemailer-mailgun-transport#116]
On project start I'm getting a warning:
```
(node:398315) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at lazyUndici (node:internal/bootstrap/pre_execution:188:5)
    at get (node:internal/bootstrap/pre_execution:204:16)
    at 556 (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:27405)
    at r (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:98812)
    at 955 (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:10905)
    at r (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:98812)
    at 765 (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:2419)
    at r (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:98812)
    at 990 (/home/epaminond/project/node_modules/mailgun.js/dist/mailgun.js:2:1871)
```
It's node 18.0.0 and I assume this warning is coming from [mailgun.js bug](https://github.com/mailgun/mailgun.js/blob/e254977b02be3ee8733621d2634bd71b3ca1ab43/CHANGELOG.md#bug-fixes-18) that was fixed in mailgun.js 3.5.7.

nodemailer-mailgun-transport [depends on mailgun.js 3.3.0](https://github.com/orliesaurus/nodemailer-mailgun-transport/blob/master/package.json#L39) - so possibly this could be the source. Would it be possible to upgrade dependency to at least 3.5.7 or newer?

**Comment by zacharytyhacz** [comment]
Related: https://github.com/mailgun/mailgun.js/issues/275

**Comment by orliesaurus** [comment]
Feel free to open PRs to upgrade @zacharytyhacz or @epaminond

**Comment by zacharytyhacz** [comment]
Mailgun just upgraded to version 7 with a fix

https://github.com/mailgun/mailgun.js/releases/tag/v7.0.0

**Comment by markstos** [comment]
Maybe this can be closed since Mailgun.js was upgraded to > 7 in September 2022:

https://github.com/orliesaurus/nodemailer-mailgun-transport/commit/ee9c005edf366aef7c0b627e257af9a0dfb53c0e
