### ISSUE TITLE
Not allow array on 'to' field?

### ISSUE THREAD

**Issue by Ferrari** [orliesaurus/nodemailer-mailgun-transport#56]
It ok to pass an array as receiver (e.g., to: ['a@abc.com', 'b@abc.com']) if we want to send to multiple receivers at once. However, after upgrade to v1.3 it seems not work anymore and will show following error messages.
```
{ Error: 'to' parameter is not a valid address. please check documentation
    at IncomingMessage.<anonymous> (/Users/sylee/PositiveGrid/internal-modules/pg-mailer/node_modules/nodemailer-mailgun-transport/node_modules/mailgun-js/lib/request.js:309:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: 400 } { message: '\'to\' parameter is not a valid address. please check documentation' }
```
It's ok when I tried downgrade to v1.2.x

**Comment by orliesaurus** [comment]
```
 to: [{name:'Mary', address:'mary@differentexample.com'}, {address:'john@anotherexample.com'}]
```

**Comment by orliesaurus** [comment]
also cc'in @ADumaine

**Comment by Ferrari** [comment]
@orliesaurus object parameter works fine, only array will return error.

**Comment by Ferrari** [comment]
Any plan publish a new version include this patch?

**Comment by orliesaurus** [comment]
Very soon

**Comment by orliesaurus** [comment]
Donezo @Ferrari <3 Thank you for your patience
